name: envGoogle
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pip
  - pip:
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
